version: "3.9"
services:
  
  mysql:
    image: "mysql:8"
    environment:
      - MYSQL_USER=wp
      - MYSQL_PASSWORD=secret
      - MYSQL_DATABASE=wpinterview
      - MYSQL_ROOT_PASSWORD=verysecret

  httpbin:
    image: "kennethreitz/httpbin"

  server:
    build: .
    ports:
      - "8080:8080"
    links:
      - mysql
      - worker
    depends_on:
      - mysql
      - worker
    environment:
      - DB_URL=mysql
      - DB_USER=wp
      - DB_NAME=wpinterview
      - DB_PASSWORD=secret
    command: ["wait-for-it.sh", "-t", "360", "mysql:3306", "--", "app", "--server"]

  worker:
    build: .
    links:
      - mysql
      - httpbin
    depends_on:
      - mysql
    environment:
      - DB_URL=mysql
      - DB_USER=wp
      - DB_NAME=wpinterview
      - DB_PASSWORD=secret
    command: ["wait-for-it.sh", "-t", "360", "mysql:3306", "--", "app", "--worker"]
